---
name: "Release CI"
permissions: read-all
on:
  push:
    branches:
      - main

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          nextVersion="$(gh release view --json name --jq '.name' | cut -d ' ' -f2 | awk -F. -v OFS=. '{$NF += 1 ; print}')"
          echo 'NEXT_VERSION='$nextVersion >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          gh release create "v${NEXT_VERSION}" -t "Release ${NEXT_VERSION}" -n "Release ${NEXT_VERSION}" --generate-notes --latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

